# -*- coding: utf-8 -*-
"""데이터분석 연습 day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6IoM5-XEAE8ys3h66HMKEjl58b6V0ei

##🔄 **[Day 1&2 복습]**


### **실습 데이터**
  ```
data = {
    '반': ['A반', 'A반', 'B반', 'B반', 'C반', 'C반'],
    '이름': ['철수', '영희', '민수', '지민', '구름', '바람'],
    '국어': [90, 80, 70, 60, 100, 90],
    '수학': [85, 95, 80, 75, 90, 80]
}
```
"""

import pandas as pd

data = {
    '반': ['A반', 'A반', 'B반', 'B반', 'C반', 'C반'],
    '이름': ['철수', '영희', '민수', '지민', '구름', '바람'],
    '국어': [90, 80, 70, 60, 100, 90],
    '수학': [85, 95, 80, 75, 90, 80]
}

df_score = pd.DataFrame(data)

print("🏫 학생 성적 데이터 준비 완료!\n\n", df_score)

#[👨‍🏫 복습문제] 우리 반의 에이스를 찾아라! 'A반' 학생 중에서 국어 점수가 85점 이상인 학생만 뽑아보세요.
# (힌트: 조건이 2개니까 &와 ()를 써야겠죠?)
aces = df_score[(df_score['반'] == 'A반') & (df_score['국어'] >= 85)]
print(aces)

"""##📅 **Day 3: 끼리끼리 묶어서 계산하기 (groupby)**

지금까진 전체 평균만 구했죠?

그런데 선생님이 "그래서 A반 평균이 몇 점인데? B반은?" 하고 물어보면 어떡할까요?

일일이 필터링해서 구하면 퇴근 못 합니다.

이럴 때 **groupby**를 씁니다.

---

**[공식]** **`df.groupby('묶을기준열')['계산할열'].함수( )`**

---

"""

#[👨‍🏫 연습문제] 반별 수학 평균 구하기 : 한번 '반별'로 '국어' 점수의 '평균(mean)'을 구해서, 어느 반이 국어를 제일 잘하는지 알아봅시다.
# kor_avg_by_class = df_score.groupby('묶을기준열')['계산할열'].함수()

kor_avg_by_class = df_score.groupby('반')['국어'].mean()
print(kor_avg_by_class)

#[👨‍🏫 연습문제] 반별 수학 평균 구하기 : 이번엔 '반별'로 '수학' 점수의 '평균(mean)'을 구해서, 어느 반이 수학을 제일 잘하는지 알아봅시다.

math_avg_by_class = df_score.groupby('반')['수학'].mean()
print(math_avg_by_class)

#[👨‍🏫 연습문제] 반별 인원수(count) 세기 (student_cnt로 변수지정)
student_cnt = df_score.groupby('반')['이름'].count()
print(student_cnt)